# Generated by Django 3.1.7 on 2021-03-30 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210330_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 10, 44, 41, 836316, tzinfo=utc)),
        ),
    ]
